name: running the powershell script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: pacticetest.azurecr.io
    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          sudo az login --username nishani.12000526@lpu.in --password Njohn526#
          sudo az acr login -n pacticetest --username pacticetest --password KxRDve1stf0tFLWIzIq7FdG08Q4MtwkYuJS+1zcyH6+ACRD0IVRn
          $acrName = "pacticetest"
          sudo az acr repository show-tags --name $acrName --repository pacticetest/pacticetest
        azPSVersion: "latest"
        
