name: running the powershell script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: pacticetest.azurecr.io
    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          sudo az login -n pacticetest
          sudo az acr login -n pacticetest --username pacticetest --password KxRDve1stf0tFLWIzIq7FdG08Q4MtwkYuJS+1zcyH6+ACRD0IVRn
          $acrName = "pacticetest"
          $acrRepository = "pacticetest/pacticetest"
          $maxTags = 1
          $tagsCount = (az acr repository show-tags --name $acrName --repository $acrRepository).length-2
          #if ($tagsCount -gt $maxTags){ az acr repository show-tags -n $acrName --repository $acrRepository --orderby time_asc --top 1 --query "[0]" --output tsv | foreach { az acr repository delete --name $acrName --image ${acrRepository}:$_ --yes } }
        azPSVersion: "latest"
        
